language: c
sudo: true
dist: trusty

#addons:
#  apt:
#    packages:
#      - clang

compiler:
#  - clang
  - gcc
#  - scan-build

#matrix:
#  include:
#    - os: osx
#      compiler: clang

script: ./.travis.sh
