/*
 * Copyright 2016 Jerry Jacobs. All rights reserved.
 * Use of this source code is governed by the MIT
 * license that can be found in the LICENSE file.
 */
#ifndef STLINK2_SEMIHOSTING_H_
#define STLINK2_SEMIHOSTING_H_

#include <stdbool.h>

enum stlink2_semihosting_operations {
	STLINK2_SEMIHOSTING_OP_SYS_OPEN        = 0x01,
	STLINK2_SEMIHOSTING_OP_SYS_CLOSE       = 0x02,
	STLINK2_SEMIHOSTING_OP_SYS_WRITEC      = 0x03,
	STLINK2_SEMIHOSTING_OP_SYS_WRITE0      = 0x04,
	STLINK2_SEMIHOSTING_OP_SYS_WRITE       = 0x05,
	STLINK2_SEMIHOSTING_OP_SYS_READ        = 0x06,
	STLINK2_SEMIHOSTING_OP_SYS_READC       = 0x07,
	STLINK2_SEMIHOSTING_OP_SYS_IS_ERROR    = 0x08,
	STLINK2_SEMIHOSTING_OP_SYS_ISTTY       = 0x09,
	STLINK2_SEMIHOSTING_OP_SYS_CLOCK       = 0x10,
	STLINK2_SEMIHOSTING_OP_SYS_TIME        = 0x11,
	STLINK2_SEMIHOSTING_OP_SYS_SYSTEM      = 0x12,
	STLINK2_SEMIHOSTING_OP_SYS_ERRNO       = 0x13,
	STLINK2_SEMIHOSTING_OP_SYS_GET_CMDLINE = 0x15,
	STLINK2_SEMIHOSTING_OP_SYS_HEAPINFO    = 0x16,
	STLINK2_SEMIHOSTING_EXCEPTION          = 0x18,
	STLINK2_SEMIHOSTING_OP_SYS_SEEK        = 0x0a,
	STLINK2_SEMIHOSTING_OP_SYS_FLEN        = 0x0c,
	STLINK2_SEMIHOSTING_OP_SYS_TMPNAM      = 0x0d,
	STLINK2_SEMIHOSTING_OP_SYS_REMOVE      = 0x0e,
	STLINK2_SEMIHOSTING_OP_SYS_RENAME      = 0x0f,
	STLINK2_SEMIHOSTING_OP_SYS_ELAPSED     = 0x30,
	STLINK2_SEMIHOSTING_OP_SYS_TICKFREQ    = 0x31
};

enum stlink2_semihosting_exception {
	STLINK2_SEMIHOSTING_EXCEPTION_BRANCH_THROUGH_ZERO = 0x20000,
	STLINK2_SEMIHOSTING_EXCEPTION_UNDEFINED_INSTR     = 0x20001,
	STLINK2_SEMIHOSTING_EXCEPTION_SOFTWARE_IRQ        = 0x20002,
	STLINK2_SEMIHOSTING_EXCEPTION_PREFETCH_ABORT      = 0x20003,
	STLINK2_SEMIHOSTING_EXCEPTION_APPLICATION_EXIT    = 0x20026
};

bool stlink2_semihosting(struct stlink2 *dev);

#endif /* STLINK2_SEMIHOSTING_H_ */
